
# Color palette for the UI
import platform

distro_palette = {
  "redhat": [
      ('body', 'black', 'light gray'),
      ('message', 'light gray', 'black'),
      ('reversed', 'light gray', 'black'),
      ('reversed_green', 'light gray', 'dark green'),
      ('reversed_red', 'light gray', 'dark red'),
      ('enabled_input', 'white', 'dark blue'),
      ('bkgnd_white', 'black', 'white'),
      ('error_message', 'white', 'dark red'),
      ('warning_message', 'black', 'brown'),
      ('error_box', 'dark red', 'light gray'),
      ('key', 'light cyan', 'black', 'underline'),
      ('title', 'white', 'dark red'),
      ('active_step', 'black', 'light gray'),
      ('inactive_step', 'white', 'dark red'),
      ('editbox', 'black', 'light gray'),
      ('buttn', 'black', 'dark cyan'),
      ('buttnf', 'white', 'dark blue', 'bold'),
      ('pg_normal', 'white', 'dark blue'),
      ('pg_complete', 'white', 'white')
  ],
  "fedora": [
        ('body', 'black', 'light gray'),
        ('message', 'light gray', 'black'),
        ('reversed', 'dark blue', 'white'),
        ('reversed_green', 'light gray', 'dark green'),
        ('reversed_red', 'light gray', 'dark red'),
        ('enabled_input', 'white', 'dark blue'),
        ('bkgnd_white', 'black', 'white'),
        ('error_message', 'white', 'dark red'),
        ('warning_message', 'black', 'brown'),
        ('error_box', 'dark red', 'light gray'),
        ('key', 'light cyan', 'black', 'underline'),
        ('title', 'white', 'dark blue'),
        ('active_step', 'black', 'light gray'),
        ('inactive_step', 'white', 'dark blue'),
        ('editbox', 'black', 'light gray'),
        ('buttn', 'black', 'dark cyan'),
        ('buttnf', 'white', 'dark blue', 'bold'),
        ('pg_normal', 'white', 'dark blue'),
        ('pg_complete', 'white', 'white')
    ],
  "centos": [
        ('body', 'black', 'light gray'),
        ('message', 'light gray', 'black'),
        ('reversed', 'light gray', 'black'),
        ('reversed_green', 'light gray', 'dark green'),
        ('reversed_red', 'light gray', 'dark red'),
        ('enabled_input', 'white', 'dark blue'),
        ('bkgnd_white', 'black', 'white'),
        ('error_message', 'white', 'dark red'),
        ('warning_message', 'black', 'brown'),
        ('error_box', 'dark red', 'light gray'),
        ('key', 'light cyan', 'black', 'underline'),
        ('title', 'white', 'brown'),
        ('active_step', 'black', 'light gray'),
        ('inactive_step', 'white', 'dark blue'),
        ('editbox', 'black', 'light gray'),
        ('buttn', 'black', 'dark cyan'),
        ('buttnf', 'white', 'dark blue', 'bold'),
        ('pg_normal', 'white', 'dark blue'),
        ('pg_complete', 'white', 'white')
    ],
  "ubuntu": [
        ('body', 'black', 'light gray'),
        ('message', 'light gray', 'black'),
        ('reversed', 'light gray', 'black'),
        ('reversed_green', 'light gray', 'dark green'),
        ('reversed_red', 'light gray', 'dark red'),
        ('enabled_input', 'white', 'dark blue'),
        ('bkgnd_white', 'black', 'white'),
        ('error_message', 'white', 'dark red'),
        ('warning_message', 'black', 'brown'),
        ('error_box', 'dark red', 'light gray'),
        ('key', 'light cyan', 'black', 'underline'),
        ('title', 'white', 'dark magenta'),
        ('active_step', 'black', 'light gray'),
        ('inactive_step', 'white', 'dark magenta'),
        ('editbox', 'black', 'light gray'),
        ('buttn', 'black', 'dark cyan'),
        ('buttnf', 'white', 'dark blue', 'bold'),
        ('pg_normal', 'white', 'dark blue'),
        ('pg_complete', 'white', 'white')
    ],
  "suse": [
        ('body', 'black', 'light gray'),
        ('message', 'light gray', 'black'),
        ('reversed', 'light gray', 'black'),
        ('reversed_green', 'light gray', 'dark green'),
        ('reversed_red', 'light gray', 'dark red'),
        ('enabled_input', 'white', 'dark blue'),
        ('bkgnd_white', 'black', 'white'),
        ('error_message', 'white', 'dark red'),
        ('warning_message', 'black', 'brown'),
        ('error_box', 'dark red', 'light gray'),
        ('key', 'light cyan', 'black', 'underline'),
        ('title', 'white', 'dark green'),
        ('active_step', 'black', 'light gray'),
        ('inactive_step', 'white', 'dark green'),
        ('editbox', 'black', 'light gray'),
        ('buttn', 'black', 'dark cyan'),
        ('buttnf', 'white', 'dark blue', 'bold'),
        ('pg_normal', 'white', 'dark blue'),
        ('pg_complete', 'white', 'white')
    ],
  "unknown": [
        ('body', 'light gray', 'black'),
        ('message', 'light gray', 'black'),
        ('reversed', 'black', 'light gray'),
        ('reversed_green', 'light gray', 'dark green'),
        ('reversed_red', 'light gray', 'dark red'),
        ('enabled_input', 'white', 'dark blue'),
        ('bkgnd_white', 'black', 'white'),
        ('error_message', 'white', 'dark red'),
        ('warning_message', 'black', 'brown'),
        ('error_box', 'dark red', 'light gray'),
        ('key', 'light cyan', 'black', 'underline'),
        ('title', 'black', 'light gray'),
        ('active_step', 'light gray', 'black'),
        ('inactive_step', 'black', 'light gray'),
        ('editbox', 'black', 'light gray'),
        ('buttn', 'black', 'dark cyan'),
        ('buttnf', 'white', 'dark blue', 'bold'),
        ('pg_normal', 'white', 'dark blue'),
        ('pg_complete', 'white', 'white')
    ]
}

distro = platform.linux_distribution(full_distribution_name=False)[0]

# account for SuSE and openSuSE
if "suse" in distro.lower():
    distro = 'suse'

palette = distro_palette.get(distro.lower(),
                             distro_palette['unknown'])
